feat(api-v2): Add support for text file upload
dasch-swiss/knora-api pull request #1664
Opened 2020-06-29 11:07 UTC by benjamingeer

2020-09-28 13:55 UTC, benjamingeer commented
Skipping `ClientApiRouteE2ESpec` because it keeps failing with this error, despite everything we've tried: 

```
Failed to get test data: {"knora-api:error":"akka.pattern.AskTimeoutException: Ask timed out on
[Actor[akka://E2ETest/user/applicationManager#-1049986081]] after [5000 ms]. Message of type
[org.knora.webapi.messages.admin.responder.usersmessages.UserGetADM] was sent by
[Actor[akka://E2ETest/user/applicationManager#-1049986081]].
```

2020-09-28 22:52 UTC, subotic commented
@benjamingeer @SepidehAlassi  could you please make sure to fix this test either in this PR or as the first next thing? If you decide to ignore it in this PR, please open an issue on YouTrack. This test is also failing on `develop`.

2020-09-29 05:41 UTC, benjamingeer commented
> @benjamingeer @SepidehAlassi  could you please make sure to fix this test either in this PR or as the first next thing? If you decide to ignore it in this PR, please open an issue on YouTrack. This test is also failing on `develop`.

We're planning to redesign it in the next sprint, using your idea of collecting the test data as a side effect of running the E2E tests.

2020-09-29 07:50 UTC, subotic commented
cool, great 👍

2020-09-29 11:01 UTC, SepidehAlassi requested changes
Thanks for this, please see my comment regarding work around for DSP-711

2020-09-29 11:01 UTC, SepidehAlassi commented on webapi/src/main/scala/org/knora/webapi/store/iiif/SipiConnector.scala
> +            // Workaround for https://dasch.myjetbrains.com/youtrack/issue/DSP-711
@benjamingeer it seems like Lukas has already fixed the issue of DSP-711, see [his response](https://dasch.myjetbrains.com/youtrack/issue/DSP-711#focus=Comments-4-1112.0-0) should this workaround be removed in this PR or later?

2020-09-29 16:43 UTC, SepidehAlassi approved these changes
@benjamingeer thanks for your work. As agreed, please make a new PR with the new version of SIPI.

2020-09-29 16:50 UTC, subotic commented
PR for updating Sipi: #1721

2020-09-29 18:05 UTC, benjamingeer commented
@SepidehAlassi Thanks for reviewing!

2020-09-29 19:13 UTC, merged